markdown: redcarpet
permalink: /:title.html
url: http://jiyidian.com
lsi: true
pygments: true
safe: true
auto: true

# presonal config
title: 第八个记忆

author:
  name: Debug0Man
  nickname: Debug0Man
  email: debug0man@yahoo.com.cn
  gmail: debug0man@yahoo.com.cn
  site: http://jiyidian.com

seo: 
  keyword: 
  description: 
config:
  js_dir:
  img_dir:
  css_dir:
